<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE parametre [
  <!ELEMENT parametre (obsah, generovat-titulny-slajd, cislovanie-slajdov, tmava-tema, titulny-slajd)>
  <!ELEMENT obsah (#PCDATA)>
  <!ELEMENT generovat-titulny-slajd (#PCDATA)>
  <!ELEMENT cislovanie-slajdov (#PCDATA)>
  <!ELEMENT tmava-tema (#PCDATA)>
  <!ELEMENT titulny-slajd (#PCDATA)>
]>
<parametre>
  <obsah>true</obsah>
  <generovat-titulny-slajd>true</generovat-titulny-slajd>
  <cislovanie-slajdov>true</cislovanie-slajdov>
  <tmava-tema>false</tmava-tema>
  <titulny-slajd>nazov,podnadpis,oddelovac</titulny-slajd>
</parametre>