=== MatusPilnan/wpub-prezentacia/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="prezentacia">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="info">
          <xs:complexType>
            <xs:all>
              <xs:element name="nazov" type="xs:string" minOccurs="1"/>
              <xs:element name="podnadpis" type="xs:string" minOccurs="0"/>
              <xs:element name="autor" type="xs:string" minOccurs="0"/>
            </xs:all>
          </xs:complexType>
        </xs:element>
        <xs:element name="slajd" maxOccurs="unbounded">
          <xs:complexType>
            <xs:choice>
              <xs:element name="text" type="xs:string" />
              <xs:element name="obrazok">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="zdroj" use="required" type="xs:anyURI"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="zoznam">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="polozka-zoznamu" maxOccurs="unbounded" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="cislovany" type="xs:boolean" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:choice>
            <xs:attribute name="nadpis" type="xs:string"/>
          </xs:complexType>
        </xs:element>  
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MatusPilnan/wpub-prezentacia/prezentacia.xml
<?xml version="1.0" encoding="UTF-8"?>
<prezentacia 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schema.xsd">
  <info>
    <nazov>Tvorba prezentácie v XML</nazov>
    <podnadpis>Neviem o tom prakticky nič ale to mi nebráni spraviť o tom prezentáciu 😉</podnadpis>
    <autor>Matúš Pilňan</autor>
  </info>
  <slajd nadpis="Úvod">
    <text>
      Dostali sme za úlohu spraviť prezentáciu s pomocou XML a XSLT. Na validáciu XML sme mohli použiť DTD, XML Schema alebo niečo čoho meno si nepamätám.
      Rozhodol som sa použiť XSD lebo tie zvyšné dve sa javia ako dosť hnoj...
    </text>
  </slajd>
  <slajd nadpis="Čo treba spraviť?">
    <zoznam cislovany="false">
      <polozka-zoznamu>Ukážková prezentácia (XML)</polozka-zoznamu>
      <polozka-zoznamu>Opis štruktúry (XSD)</polozka-zoznamu>
      <polozka-zoznamu>Transformácia do XHTML (XSLT)</polozka-zoznamu>
      <polozka-zoznamu>Transformácia do FO a PDF (XSLT)</polozka-zoznamu>
    </zoznam>
  </slajd>
  <slajd nadpis="Aj obrázok by som dal...">
    <obrazok zdroj="D:/Users/MatusPilnan/Pictures/89593.png">...takže tu je Danko Dangl.</obrazok>
  </slajd>
  <slajd nadpis="A vlastne ešte zoradený zoznam">
    <zoznam cislovany="true">
      <polozka-zoznamu>Prvý prvok</polozka-zoznamu>
      <polozka-zoznamu>Druhá položka</polozka-zoznamu>
      <polozka-zoznamu>Štvrtá položka</polozka-zoznamu>
      <polozka-zoznamu>To sú ale šprímy čo?</polozka-zoznamu>
    </zoznam>
  </slajd>
</prezentacia>
